/*
包含n个接口请求模块
*/
import ajax from 'ajax'
// [根据经纬度获取位置详情](#1根据经纬度获取位置详情)
export const reqAddress = (geohash) => ajax(`/position/${geohash}`)
// [获取食品分类列表](#2获取食品分类列表)
export const reqFoodTypes = () => ajax('/index_category')
// [根据经纬度获取商铺列表](#3根据经纬度获取商铺列表)
// export const reqShopList = (a, b) => ajax('shops', { longitude:a, latitude:b })
export const reqShopList = (longitude, latitude) => ajax('/shops', { longitude, latitude })
// [根据经纬度和关键字搜索商铺列表](#4根据经纬度和关键字搜索商铺列表)
export const reqSearch = (geohash, keyword) => ajax('/search_shops', { geohash, keyword })
// [获取一次性验证码](#5获取一次性验证码)
export const reqCaptcha = () => ajax('/captcha')
// [用户名密码登陆](#6用户名密码登陆)
export const reqPwd = (name, pwd, captcha) => ajax('login_pwd', { name, pwd, captcha }, 'post')
// [发送短信验证码](#7发送短信验证码)
export const reqPhoneCode = (phone) => ajax('/sendcode', { phone })
// [手机号验证码登陆](#8手机号验证码登陆)
export const reqPhoneLogin = (phone, code) => ajax('/login_sms', { phone, code }, 'post')
// [根据会话获取用户信息](#9根据会话获取用户信息)
export const reqGetUse = () => ajax('/userinfo')
// [用户登出](#10用户登出)
export const reqLogout = () => ajax('/logout')
